### ISSUE TITLE
Demo: Something went wrong. Refresh to try again.

### ISSUE THREAD

**Issue by oneezy** [vitalikda/chatbase-sveltekit#1]
Great talk **Vitaly**! 

Looks like there's an issue on the [demo](https://chatbaseapp.vercel.app/). Any Idea?

![image](https://github.com/vitalikda/chatbase-sveltekit/assets/7369575/d755573d-ed84-4fc2-85fb-10580fa5d3a8)

**Comment by vitalikda** [comment]
@oneezy thank you for bringing this up

Unfortunately, Grafbase has ceased support for SSE, which is causing this issue 

 I will update the README to reflect the current state of the demo and its compatibility details
